homework10/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'trips/index'

  root 'trips#index'

  resources :trips do
    resources :entries
  end 

end

homework10/app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :trip
end

homework10/app/models/trip.rb
class Trip < ActiveRecord::Base
	belongs_to :user
	has_many :entries
	validates :title, presence: true
					# length: {minimum: 3}
end

homework10/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

homework10/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

homework10/app/controllers/entries_controller.rb
class EntriesController < ApplicationController

	def create
		@trip = Trip.find(params[:trip_id])
		@entry = @trip.entries.create(entry_params)
		redirect_to trip_path(@trip)
	end

	def edit
		@trip = Trip.find(params[:trip_id])
		@entry = @trip.entries.find(params[:id])
	end

	def update
		@trip = Trip.find(params[:trip_id])
		@entry = Entry.find(params[:id])

		if @entry.update(entry_params)
			redirect_to @trip
		else
			render 'edit'
		end
	end

	def destroy
    	@trip = Trip.find(params[:trip_id])
    	@entry = @trip.entries.find(params[:id])
    	@entry.destroy
    	redirect_to trip_path(@trip)
  	end

end

private
    def entry_params
      params.require(:entry).permit(:date, :location, :memory)
    end

homework10/app/controllers/trips_controller.rb
class TripsController < ApplicationController
	
	def index
		@trips = Trip.all
	end

	def show
		@trip = Trip.find(params[:id])
		@entries = @trip.entries
	end

	def new
		@trip = Trip.new
	end

	def edit
		@trip = Trip.find(params[:id])
	end

	def create
		@trip = Trip.new(trip_params)

		if @trip.save
			redirect_to @trip
		else
			render 'new'
		end 
	end 

	def update
		@trip = Trip.find(params[:id])
		if @trip.update(trip_params)
			redirect_to @trip
		else
			render 'edit'
		end
	end

	def destroy
		@trip = Trip.find(params[:id])
		@trip.destroy
		redirect_to trips_path
	end

	private 
		def trip_params
			params.require(:trip).permit(:title, :dates, :region, :description)
	end
end 

homework10/app/helpers/application_helper.rb
module ApplicationHelper
end

homework10/app/helpers/entries_helper.rb
module EntriesHelper
end

homework10/app/helpers/trips_helper.rb
module TripsHelper
end

homework10/app/views/entries/_entry.html.erb
<p>
  <strong>Date:</strong>
  <%= entry.date %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= entry.location %>
</p>

<p>
  <strong>Best Memory:</strong>
  <%= entry.memory %>
</p>

<p>
  <%= link_to 'Edit Entry', edit_trip_entry_path(entry.trip, entry) %>
  <%= link_to 'Destroy Entry', [entry.trip, entry],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

homework10/app/views/entries/edit.html.erb
<h1>Edit your entry</h1>
<%= form_for @entry, url: trip_entry_path do |f| %>
  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date, :placeholder => 'YYYY/MM/DD' %>
  </p>
  </p>
  <p>
    <%= f.label :location %><br>
    <%= f.text_area :location, :placeholder => 'Where were you?' %>
  </p>
    <p>
    <%= f.label :memory %><br>
    <%= f.text_area :memory, :placeholder => 'Favorite part of the day?' %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

homework10/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework10</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<p>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>


<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<%= yield %>

</body>
</html>

homework10/app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>

  <% if @trip.errors.any? %>
	  <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited
        this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
</div>
 
<div>
    <%= f.label :region %><br>
    <%= f.text_field :region %>
</div>
 
<div>
    <%= f.label :dates %><br>
    <%= f.text_field :dates %>
</div>

<div>
    <%= f.label :description %><br>
    <%= f.text_field :description, :placeholder => 'Tell us about it!' %>
</div>
 
<div>
    <%= f.submit %>
</div>
 
<% end %>

homework10/app/views/trips/edit.html.erb
<h1>Editing <%= @trip.title %></h1>
<%= render 'form' %>

homework10/app/views/trips/index.html.erb
<h1>Listing Trips </h1>
	<%= link_to "New Trip", new_trip_path %>
	</br>

<table>
	<tr>
		<th>Name of Trip</th>
		<th>Region</th>
		<th colspan="3"></th>
	</tr>

    <% @trips.each do |trip| %>
   
	<tr>
		<td><%= trip.title %></td>
		<td><%= trip.region %></td>
		<td><%= link_to 'Show', trip_path(trip) %></td>
		<td><%= link_to 'Edit', trip_path(trip) %></td>
		<td><%= link_to 'Destroy', trip_path(trip), method: :delete, data: { confirm: 'Are you sure?' } %></td>

	</tr>
	<% end %>
</table>

homework10/app/views/trips/new.html.erb
<h1>Documenting a new trip</h1>
<%= render 'form' %>

homework10/app/views/trips/show.html.erb
<h1><%= @trip.title %></h1>
<p>Please read about my adventures in <%= @trip.region %> </p>
<p> I was there <%= @trip.dates %> </p>
<p> How I would describe my trip: <%= @trip.description %> </p>


<h2> Entries </h2>
<%= render @trip.entries %>

<h2>Add an entry:</h2>
<%= form_for([@trip, @trip.entries.build]) do |f| %>
  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date, :placeholder => 'YYYY/MM/DD' %>
  </p>
  </p>
  <p>
    <%= f.label :location %><br>
    <%= f.text_area :location, :placeholder => 'Where were you?' %>
  </p>
    <p>
    <%= f.label :memory %><br>
    <%= f.text_area :memory, :placeholder => 'Favorite part of the day?' %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', trips_path %>
<%= link_to 'Edit', edit_trip_path(@trip) %>
<%= link_to 'Destroy', trip_path(@trip), method: :delete, data: { confirm: 'Are you sure?'} %>